# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://prp-brasil.github.io/
baseurl: /lp/
title: Desenvolvimento Pessoal
email: kelvinromero@gmail.com
author: Kelvin Romero
description: >
  Kelvin Romero
copyright: 'Build with 💪 by PRP 2025'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/kelvinromero
  - title: linkedin
    url: https://linkedin.com/in/kelvinromero
